builds:
- env:
  - CGO_ENABLED=0
  goos:
    - windows
    - darwin
    - linux
    - freebsd
  goarch:
    - 386
    - amd64
    - arm64
  ignore:
    - goos: windows
      goarch: 386
archives:
-
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  filters:
    exclude:
      - "^doc"
      - "^test"
      - "^todo"
      - "^minor"
      - "^WIP"
      - "typo"
brews:
-
  commit_author:
    email: vbauerster@gmail.com
    name:  vbauerster
  description: "HTTP Download Manager with multi-parts"
  folder: Formula
  tap:
    name:  homebrew-getparty
    owner: vbauerster
  homepage: "https://github.com/vbauerster/getparty"
  test: "system  \"#{bin}/getparty --version\""
