name: Build

on:
  push:
    branches:
      - master
    tags-ignore:
      - v*
  pull_request:

permissions:
  contents: read
  pull-requests: read

defaults:
  run:
    working-directory: cmd/getparty

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - run: go build -v
