name: build

on:
  push:
    branches:
      - master
    tags-ignore:
      - v*
  pull_request:

permissions:
  contents: read
  pull-requests: read

defaults:
  run:
    working-directory: cmd/getparty

jobs:
  build:
    strategy:
      matrix:
        go-version: [stable, oldstable]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - run: go test -v
    - run: go build -v
