name: golangci-lint

on:
  push:
    branches:
      - master
    tags-ignore:
      - v*
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  golangci:
    strategy:
      matrix:
        go-version: [stable]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
