name: test

on:
  push:
    branches:
      - master
    tags-ignore:
      - v*
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    strategy:
      matrix:
        go-version: [stable, oldstable]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
    - run: go test -v ./...
